name: inflowence
dependencies:
  - python==3.10.4
  - psycopg2==2.8.6
  - pip
  - pip:
      - django==4.0.4
      - django-countries==7.3.2
      - djangorestframework==3.13.1
      - djangorestframework-simplejwt==5.1.0
      - gunicorn==20.1.0
      - Pillow==9.0.1
      - flake8==4.0.1
      - drf-yasg==1.20.0
      - django-cors-headers==3.11.0
      - django-filter==21.1.0
